Fix test that fails sometimes b/c of timing
If the computer is slow or you are unlucky, one of the tests can fail, because
the first and third commits can happen on a different second. This fixes that.
Here's an example of the failure that it fixes:

    [marca@marca-mac2 gandalf]$ go test ./repository

    ----------------------------------------------------------------------
    FAIL: repository_test.go:2163: S.TestGetLogsWithAllSortsOfSubjects

    repository_test.go:2202:
        c.Assert(history.Commits[1].CreatedAt, gocheck.Equals, history.Commits[0].Author.Date)
    ... obtained string = "Fri Jan 2 09:21:20 2015 -0800"
    ... expected string = "Fri Jan 2 09:21:21 2015 -0800"

    OOPS: 116 passed, 1 FAILED
    --- FAIL: Test (8.30s)
    FAIL
    FAIL    github.com/tsuru/gandalf/repository     8.307s